### ISSUE TITLE
docker not working

### ISSUE THREAD

**Issue by csoft-sc** [caretdev/irissqlcli#1]
I have tried the different commands for docker to get it up in order to test.
I have checked the username, password, and tried with --net host.
It just returns: [Errno -2] Name or service not known

Running IRIS on Ubuntu Server 20.04.
Superserver port is 1972
No other containers running.

Does not seem easy to get it started in the container.

**Comment by daimor** [comment]
Thanks for the report, 
sorry, forgot to update image, and how it should be ok
pull the latest version and have a look with it

**Comment by csoft-sc** [comment]
It is working now, thank you.
